# Generated by Django 3.1 on 2020-08-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200811_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jasoseol',
            old_name='autor',
            new_name='author',
        ),
    ]
